ALTER TABLE IT0021 ADD FOREIGN KEY (famsa) REFERENCES T591S (subty) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0021 ADD FOREIGN KEY (fgbld) REFERENCES T005T (land1) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0021 ADD FOREIGN KEY (fanat) REFERENCES T005T (land1) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0021 ADD FOREIGN KEY(fnmzu, title) REFERENCES T535N (art, title) ON UPDATE CASCADE ON DELETE RESTRICT;
