DELETE FROM T556B WHERE MOPGK IN ('2','3');

ALTER TABLE T556B DROP CONSTRAINT t556b_pkey;

ALTER TABLE T556B DROP COLUMN MOPGK;

ALTER TABLE T556B DROP COLUMN MOZKO;

ALTER TABLE T556B ADD PRIMARY KEY (KTART);
