CREATE TABLE IT0001 (
    PERNR BIGINT NOT NULL,
    ENDDA timestamp with time zone NOT NULL,
    BEGDA timestamp with time zone NOT NULL,
    SEQNR BIGINT,
    AEDTM timestamp with time zone NOT NULL,
    UNAME character varying(100) NOT NULL,
    BUKRS character varying(10) NOT NULL,
    WERKS character varying(10),
    PERSG character varying(10),
    PERSK character varying(10),
    VDSK1 character varying(14),
    GSBER character varying(10),
    BTRTL character varying(10),
    ABKRS character varying(10),
    KOSTL character varying(15),
    ORGEH BIGINT,
    PLANS BIGINT,
    STELL BIGINT,
    MSTBR character varying(10),
    SACHA character varying(10),
    SACHP character varying(10),
    SACHZ character varying(10),
    SNAME character varying(100),
    ENAME character varying(100),
    OTYPE character varying(10),
    SBMOD character varying(10),
    KOKRS character varying(10) 
);

ALTER TABLE IT0001 ADD PRIMARY KEY (PERNR, ENDDA, BEGDA);

ALTER TABLE IT0001 ADD FOREIGN KEY (BUKRS) REFERENCES T001(BUKRS) ON UPDATE CASCADE ON DELETE RESTRICT;

--ALTER TABLE IT0001 ADD FOREIGN KEY (WERKS) REFERENCES T500P(PERSA) ON UPDATE CASCADE ON DELETE RESTRICT;

--ALTER TABLE IT0001 ADD FOREIGN KEY (PERSG) REFERENCES T501T(PERSG) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0001 ADD FOREIGN KEY (PERSK) REFERENCES T503K(MANDT) ON UPDATE CASCADE ON DELETE RESTRICT;

--ALTER TABLE IT0001 ADD FOREIGN KEY (BTRTL) REFERENCES V_001P_ALL(BTRTL) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0001 ADD FOREIGN KEY (ABKRS) REFERENCES T549T(ABKRS) ON UPDATE CASCADE ON DELETE RESTRICT;

--ALTER TABLE IT0001 ADD FOREIGN KEY (KOSTL) REFERENCES CSKT(KOSTL) ON UPDATE CASCADE ON DELETE RESTRICT;

--ALTER TABLE IT0001 ADD FOREIGN KEY (ORGEH) REFERENCES T527X(ORGEH) ON UPDATE CASCADE ON DELETE RESTRICT;

--ALTER TABLE IT0001 ADD FOREIGN KEY (PLANS) REFERENCES T528T(PLANS) ON UPDATE CASCADE ON DELETE RESTRICT;

--ALTER TABLE IT0001 ADD FOREIGN KEY (STELL) REFERENCES T513S(STELL) ON UPDATE CASCADE ON DELETE RESTRICT;

COMMENT ON TABLE IT0001 IS 'Table for Personal Main Data';

COMMENT ON COLUMN IT0001.PERNR IS 'Personnel Number';

COMMENT ON COLUMN IT0001.ENDDA IS 'End Date';

COMMENT ON COLUMN IT0001.BEGDA IS 'Start Date';

COMMENT ON COLUMN IT0001.SEQNR IS 'Infotype Record No.';

COMMENT ON COLUMN IT0001.AEDTM IS 'Changed On';

COMMENT ON COLUMN IT0001.UNAME IS 'Changed By';

COMMENT ON COLUMN IT0001.BUKRS IS 'Company Code';

COMMENT ON COLUMN IT0001.WERKS IS 'Personnel Area';

COMMENT ON COLUMN IT0001.PERSG IS 'Employee Group';

COMMENT ON COLUMN IT0001.PERSK IS 'Employee Subgroup';

COMMENT ON COLUMN IT0001.VDSK1 IS 'Organizational Key';

COMMENT ON COLUMN IT0001.GSBER IS 'Business Area';

COMMENT ON COLUMN IT0001.BTRTL IS 'Personnel Subarea';

COMMENT ON COLUMN IT0001.ABKRS IS 'Payroll Area';

COMMENT ON COLUMN IT0001.KOSTL IS 'Cost Center';

COMMENT ON COLUMN IT0001.ORGEH IS 'Organizational Unit';

COMMENT ON COLUMN IT0001.PLANS IS 'Position';

COMMENT ON COLUMN IT0001.STELL IS 'Job Key';

COMMENT ON COLUMN IT0001.MSTBR IS 'Supervisor Area';

COMMENT ON COLUMN IT0001.SACHA IS 'Payroll Administrator';

COMMENT ON COLUMN IT0001.SACHP IS 'Pers.Administrator';

COMMENT ON COLUMN IT0001.SACHZ IS 'Time Administrator';

COMMENT ON COLUMN IT0001.SNAME IS 'Last Name First Name';

COMMENT ON COLUMN IT0001.ENAME IS 'Employee/Appl.Name';

COMMENT ON COLUMN IT0001.OTYPE IS 'Object Type';

COMMENT ON COLUMN IT0001.SBMOD IS 'Administrator Group';

COMMENT ON COLUMN IT0001.KOKRS IS 'Controlling Area';
