COMMENT ON TABLE IT0002 IS 'Personal Data';

COMMENT ON COLUMN IT0002.pernr IS 'Personnel Number';

COMMENT ON COLUMN IT0002.endda IS 'End Date';

COMMENT ON COLUMN IT0002.begda IS 'Begin Date';

COMMENT ON COLUMN IT0002.seqnr IS 'Infotype Record No.';

COMMENT ON COLUMN IT0002.AEDTM IS 'Changed on.';

COMMENT ON COLUMN IT0002.UNAME IS 'Changed By.';

COMMENT ON COLUMN IT0002.NACHN IS 'Last Name';

COMMENT ON COLUMN IT0002.CNAME IS 'Full Name';

COMMENT ON COLUMN IT0002.ART IS 'Title 1 Name Affix Type';

COMMENT ON COLUMN IT0002.TITLE IS 'Title 1';

COMMENT ON COLUMN IT0002.ART2 IS 'Title 2 Name Affix Type';

COMMENT ON COLUMN IT0002.TITLE2 IS 'Title 2';

COMMENT ON COLUMN IT0002.ART3 IS 'Title 3 Name Affix Type';

COMMENT ON COLUMN IT0002.TITLE3 IS 'Title 3';

COMMENT ON COLUMN IT0002.RUFNM IS 'Nick Name';

COMMENT ON COLUMN IT0002.KNZNM IS 'Name Format Ind.';

COMMENT ON COLUMN IT0002.ANRED IS 'Form of Address Key.';

COMMENT ON COLUMN IT0002.GESCH IS 'Gender';

COMMENT ON COLUMN IT0002.GBDAT IS 'Date of Birth';

COMMENT ON COLUMN IT0002.GBLND IS 'Country of Birth';

COMMENT ON COLUMN IT0002.GBORT IS 'Birth Place';

COMMENT ON COLUMN IT0002.SPRSL IS 'Communication Lang';

COMMENT ON COLUMN IT0002.KONFE IS 'Religion';

COMMENT ON COLUMN IT0002.FAMST IS 'Marrital Status';

COMMENT ON COLUMN IT0002.FAMDT IS 'Marrital Status Since';

COMMENT ON COLUMN IT0002.ANZKD IS 'Number of Children';
