CREATE TABLE IT0006 (
    PERNR BIGINT NOT NULL,
    INFTY character varying(4) NOT NULL,
    SUBTY character varying(4) NOT NULL,
    ENDDA timestamp with time zone NOT NULL,
    BEGDA timestamp with time zone NOT NULL,
    SEQNR BIGINT,
    AEDTM timestamp with time zone NOT NULL,
    UNAME character varying(12) NOT NULL,
    ANSSA character varying(4),
    NAME2 character varying(40),
    STRAS character varying(60),
    ORT01 character varying(40),
    ORT02 character varying(40),
    PSTLZ character varying(10),
    LAND1 character varying(3),
    TELNR character varying(14),
    ENTKM NUMERIC(5, 2),
    LOCAT character varying(40),
    STATE character varying(3),
    ENTK2 NUMERIC(5, 2),
    COM01 character varying(4),
    NUM01 character varying(20) 
);

ALTER TABLE IT0006 ADD PRIMARY KEY (PERNR, SUBTY, ENDDA, BEGDA);

ALTER TABLE IT0006 ADD FOREIGN KEY (INFTY, SUBTY) REFERENCES T591S(INFTY, SUBTY) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0006 ADD FOREIGN KEY (LAND1) REFERENCES T005T(LAND1) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0006 ADD FOREIGN KEY (STATE) REFERENCES T005U(BLAND) ON UPDATE CASCADE ON DELETE RESTRICT;

COMMENT ON TABLE IT0006 IS 'Table master for Addresses (i.e. Infotype IT0006 in SAP)';

COMMENT ON COLUMN IT0006.PERNR IS 'Personnel Number';

COMMENT ON COLUMN IT0006.INFTY IS 'Info type';

COMMENT ON COLUMN IT0006.SUBTY IS 'Subtype';

COMMENT ON COLUMN IT0006.ENDDA IS 'End Date';

COMMENT ON COLUMN IT0006.BEGDA IS 'Start Date';

COMMENT ON COLUMN IT0006.SEQNR IS 'Infotype record no.';

COMMENT ON COLUMN IT0006.AEDTM IS 'Changed On';

COMMENT ON COLUMN IT0006.UNAME IS 'Changed By';

COMMENT ON COLUMN IT0006.ANSSA IS 'Address Type';

COMMENT ON COLUMN IT0006.NAME2 IS 'Care of';

COMMENT ON COLUMN IT0006.STRAS IS 'Street and House No.';

COMMENT ON COLUMN IT0006.ORT01 IS 'City';

COMMENT ON COLUMN IT0006.ORT02 IS 'District';

COMMENT ON COLUMN IT0006.PSTLZ IS 'Postal Code';

COMMENT ON COLUMN IT0006.LAND1 IS 'Country Key';

COMMENT ON COLUMN IT0006.TELNR IS 'Telephone Number';

COMMENT ON COLUMN IT0006.ENTKM IS 'Distance in Km';

COMMENT ON COLUMN IT0006.LOCAT IS '2nd Address Line';

COMMENT ON COLUMN IT0006.STATE IS 'Region';

COMMENT ON COLUMN IT0006.ENTK2 IS 'Distance in Km';

COMMENT ON COLUMN IT0006.COM01 IS 'Communication Type';

COMMENT ON COLUMN IT0006.NUM01 IS 'Number';
