ALTER TABLE IT0022 ADD PRIMARY KEY (pernr, subty, endda, begda);

ALTER TABLE IT0022 ADD FOREIGN KEY (SLART) REFERENCES T517T (SLART) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0022 ADD FOREIGN KEY (SLAND) REFERENCES T005T (LAND1) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0022 ADD FOREIGN KEY (AUSBI) REFERENCES T518B (AUSBI) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0022 ADD FOREIGN KEY (SLABS) REFERENCES T519T (SLABS) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0022 ADD FOREIGN KEY (ANZEH) REFERENCES T538T (ZEINH) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0022 ADD FOREIGN KEY (SLTP1) REFERENCES T517X (FAART) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0022 ADD FOREIGN KEY (SLTP2) REFERENCES T517X (FAART) ON UPDATE CASCADE ON DELETE RESTRICT;
