ALTER TABLE IT0023 ADD PRIMARY KEY (pernr, endda, begda);

ALTER TABLE IT0023 ADD FOREIGN KEY (land1) REFERENCES T005T (land1) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0023 ADD FOREIGN KEY (branc) REFERENCES T016T (brsch) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0023 ADD FOREIGN KEY (TAETE) REFERENCES T513C (taete) ON UPDATE CASCADE ON DELETE RESTRICT;
