CREATE TABLE IT0009 (
    PERNR BIGINT NOT NULL,
    INFTY character varying(4) NOT NULL,
    SUBTY character varying(4) NOT NULL,
    ENDDA timestamp with time zone NOT NULL,
    BEGDA timestamp with time zone NOT NULL,
    SEQNR BIGINT,
    AEDTM timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    UNAME character varying(12) NOT NULL,
    BETRG NUMERIC (15, 2),
    WAERS character varying(10),
    ANZHL decimal(7,2),
    BNKSA character varying(4),
    ZLSCH character varying(2),
    EMFTX character varying(40),
    BKPLZ character varying(10),
    BKORT character varying(25),
    BANKS character varying(3),
    BANKL character varying(15),
    BANKN character varying(18),
    ZWECK character varying(40)
);

ALTER TABLE IT0009 ADD PRIMARY KEY (PERNR, SUBTY, ENDDA, BEGDA);

ALTER TABLE IT0009 ADD FOREIGN KEY (INFTY, SUBTY) REFERENCES T591S (INFTY, SUBTY) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0009 ADD FOREIGN KEY (ZLSCH) REFERENCES T042Z (ZLSCH) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0009 ADD FOREIGN KEY (BANKS) REFERENCES T005T (LAND1) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE IT0009 ADD FOREIGN KEY (BANKL) REFERENCES BNKA (BANKL) ON UPDATE CASCADE ON DELETE RESTRICT;

COMMENT ON TABLE IT0009 IS 'Table master for Bank Details';

COMMENT ON COLUMN IT0009.PERNR IS 'Personnel Number';

COMMENT ON COLUMN IT0009.INFTY IS 'Infotype';

COMMENT ON COLUMN IT0009.SUBTY IS 'Subtype';

COMMENT ON COLUMN IT0009.ENDDA IS 'End Date';

COMMENT ON COLUMN IT0009.BEGDA IS 'Start Date';

COMMENT ON COLUMN IT0009.SEQNR IS 'Infotype Record No.';

COMMENT ON COLUMN IT0009.AEDTM IS 'Changed On';

COMMENT ON COLUMN IT0009.UNAME IS 'Changed By';

COMMENT ON COLUMN IT0009.BETRG IS 'Standard Value';

COMMENT ON COLUMN IT0009.WAERS IS 'Payment Currency';

COMMENT ON COLUMN IT0009.ANZHL IS 'Standard Percentage';

COMMENT ON COLUMN IT0009.BNKSA IS 'Bank Details Type';

COMMENT ON COLUMN IT0009.ZLSCH IS 'Payment Method';

COMMENT ON COLUMN IT0009.EMFTX IS 'Payee';

COMMENT ON COLUMN IT0009.BKPLZ IS 'Postal Code/City';

COMMENT ON COLUMN IT0009.BKORT IS 'City';

COMMENT ON COLUMN IT0009.BANKS IS 'Bank Country';

COMMENT ON COLUMN IT0009.BANKL IS 'Bank Key';

COMMENT ON COLUMN IT0009.BANKN IS 'Bank Account';

COMMENT ON COLUMN IT0009.ZWECK IS 'Purpose';
