ALTER TABLE IT0001 ALTER COLUMN ORGEH TYPE character varying(25);

ALTER TABLE IT0001 ALTER COLUMN PLANS TYPE character varying(25);

ALTER TABLE IT0001 ALTER COLUMN STELL TYPE character varying(25);
