ALTER TABLE m_user ALTER COLUMN pernr SET NOT NULL;

ALTER TABLE m_user ALTER COLUMN endda SET NOT NULL;

ALTER TABLE m_user ALTER COLUMN begda SET NOT NULL;

ALTER TABLE m_user ADD FOREIGN KEY (pernr, endda, begda) REFERENCES IT0002 (pernr, endda, begda) ON UPDATE CASCADE ON DELETE RESTRICT;

